// Mock data for the Sidd Ahmed Community platform

export const communityMembers = [
  {
    id: "1",
    name: "Ravi Patel",
    role: "Online Coach",
    avatar: "/avatars/ravi.jpg",
    location: "San Francisco, CA",
    email: "ravi@example.com",
    bio: "Helping entrepreneurs scale their businesses with proven strategies and mindset coaching.",
    memberSince: "Jan 2024",
    tags: ["Business", "Coaching", "Mindset"],
    postsCount: 45,
    commentsCount: 128,
    spacesJoined: 8,
    isOnline: true,
    color: "bg-blue-500",
  },
  {
    id: "2",
    name: "Aisha Khan",
    role: "Business Expert / Course Strategy Mentor",
    avatar: "/avatars/aisha.jpg",
    location: "Dubai, UAE",
    email: "aisha@example.com",
    bio: "Course creator and business strategist. I help you turn your knowledge into profitable online courses.",
    memberSince: "Feb 2024",
    tags: ["Courses", "Strategy", "Marketing"],
    postsCount: 32,
    commentsCount: 95,
    spacesJoined: 6,
    isOnline: true,
    color: "bg-purple-500",
  },
  {
    id: "3",
    name: "Robert Fox",
    role: "Business Coach",
    avatar: "/avatars/robert.jpg",
    location: "New York, NY",
    email: "robert@example.com",
    bio: "20+ years of experience helping startups and established businesses reach their full potential.",
    memberSince: "Mar 2024",
    tags: ["Business", "Startups", "Growth"],
    postsCount: 28,
    commentsCount: 67,
    spacesJoined: 5,
    isOnline: false,
    color: "bg-green-500",
  },
  {
    id: "4",
    name: "Kwame Adebayo",
    role: "Musician",
    avatar: "/avatars/kwame.jpg",
    location: "Playa del Carmen, MX",
    email: "kwame@example.com",
    bio: "Blending traditional African rhythms with modern beats. Music is my meditation.",
    memberSince: "Apr 2024",
    tags: ["Music", "Creativity", "Wellness"],
    postsCount: 19,
    commentsCount: 42,
    spacesJoined: 4,
    isOnline: true,
    color: "bg-orange-500",
  },
  {
    id: "5",
    name: "Kristin Watson",
    role: "Admin",
    avatar: "/avatars/kristin.jpg",
    location: "Austin, TX",
    email: "kristin@example.com",
    bio: "Community manager and admin. Here to help you get the most out of this community!",
    memberSince: "Jan 2024",
    tags: ["Admin", "Support", "Community"],
    postsCount: 156,
    commentsCount: 312,
    spacesJoined: 12,
    isOnline: true,
    color: "bg-pink-500",
  },
  {
    id: "6",
    name: "Mei Wong",
    role: "Life Coach in Training",
    avatar: "/avatars/mei.jpg",
    location: "Singapore",
    email: "mei@example.com",
    bio: "On my journey to becoming a certified life coach. Sharing what I learn along the way.",
    memberSince: "May 2024",
    tags: ["Coaching", "Personal Growth", "Learning"],
    postsCount: 12,
    commentsCount: 38,
    spacesJoined: 7,
    isOnline: false,
    color: "bg-teal-500",
  },
  {
    id: "7",
    name: "Carlos Ramirez",
    role: "Solopreneur",
    avatar: "/avatars/carlos.jpg",
    location: "Miami, FL",
    email: "carlos@example.com",
    bio: "Building my dream business one day at a time. Passionate about freedom and flexibility.",
    memberSince: "Jun 2024",
    tags: ["Solopreneur", "Freedom", "Business"],
    postsCount: 8,
    commentsCount: 24,
    spacesJoined: 5,
    isOnline: true,
    color: "bg-indigo-500",
  },
];

export const posts = [
  {
    id: "1",
    author: communityMembers[0],
    title: "How I scaled my coaching business to 6 figures",
    body: "After 3 years of trial and error, I finally cracked the code. Here are the 5 key strategies that made all the difference in my journey...",
    image: null,
    likes: 47,
    comments: 23,
    likedBy: [communityMembers[1], communityMembers[2], communityMembers[3]],
    timestamp: "2h ago",
    isPinned: true,
    space: "Wins",
  },
  {
    id: "2",
    author: communityMembers[1],
    title: "New course launching next week!",
    body: "I'm thrilled to announce my new course on building and selling online courses. Early bird pricing available for community members only.",
    image: "/posts/course-launch.jpg",
    likes: 34,
    comments: 15,
    likedBy: [communityMembers[0], communityMembers[4], communityMembers[5]],
    timestamp: "5h ago",
    isPinned: false,
    space: "Announcements",
  },
  {
    id: "3",
    author: communityMembers[2],
    title: "Weekly mindset challenge: Day 1",
    body: "Starting the week with intention. Today's challenge: Write down 3 things you're grateful for and share them below!",
    image: null,
    likes: 28,
    comments: 42,
    likedBy: [communityMembers[3], communityMembers[5], communityMembers[6]],
    timestamp: "1d ago",
    isPinned: false,
    space: "Discussions",
  },
  {
    id: "4",
    author: communityMembers[4],
    title: "Welcome to our newest members!",
    body: "We have 15 new community members this week! Please take a moment to introduce yourself in the Say Hello space.",
    image: null,
    likes: 56,
    comments: 18,
    likedBy: [communityMembers[0], communityMembers[1], communityMembers[2]],
    timestamp: "2d ago",
    isPinned: true,
    space: "Announcements",
  },
];

export const spaces = [
  {
    category: "Welcome",
    items: [
      { id: "start-here", name: "Start Here", icon: "rocket" },
      { id: "say-hello", name: "Say Hello", icon: "hand" },
    ],
  },
  {
    category: "Community",
    items: [
      { id: "announcements", name: "Announcements", icon: "megaphone" },
      { id: "resources", name: "Resources", icon: "folder" },
      { id: "discussions", name: "Discussions", icon: "message-circle" },
      { id: "wins", name: "Wins", icon: "trophy" },
    ],
  },
  {
    category: "Events",
    items: [{ id: "recordings", name: "Recordings", icon: "video" }],
  },
];

export const chatChannels = [
  { id: "general", name: "general", unread: 0 },
  { id: "announcements", name: "announcements", unread: 3 },
  { id: "off-topic", name: "off-topic", unread: 0 },
  { id: "introductions", name: "introductions", unread: 1 },
  { id: "wins", name: "wins", unread: 0 },
];

export const chatMessages = [
  {
    id: "1",
    author: communityMembers[0],
    message: "Hey everyone! Just wanted to check in and see how your week is going?",
    timestamp: "10:32 AM",
    reactions: [
      { emoji: "👋", count: 2 },
      { emoji: "❤️", count: 1 },
    ],
  },
  {
    id: "2",
    author: communityMembers[1],
    message: "Going great! Just finished recording my new course module. Feeling accomplished!",
    timestamp: "10:45 AM",
    reactions: [
      { emoji: "🙌", count: 3 },
      { emoji: "🎉", count: 2 },
    ],
  },
  {
    id: "3",
    author: communityMembers[3],
    message: "That's awesome Aisha! Can't wait to check it out. Anyone up for the afternoon workshop?",
    timestamp: "11:02 AM",
    reactions: [{ emoji: "✅", count: 4 }],
  },
];

export const courses = [
  {
    id: "1",
    title: "Business Growth Fundamentals",
    category: "Business Growth",
    thumbnail: "/courses/business-growth.jpg",
    lessons: 12,
    startDate: "Started Jan 15",
    progress: 65,
    isNew: false,
    instructor: communityMembers[0],
  },
  {
    id: "2",
    title: "Course Creation Masterclass",
    category: "Basics & Fundamentals",
    thumbnail: "/courses/course-creation.jpg",
    lessons: 8,
    startDate: "Starts Mar 20",
    progress: 0,
    isNew: true,
    instructor: communityMembers[1],
  },
  {
    id: "3",
    title: "Mindset for Success",
    category: "Mindset",
    thumbnail: "/courses/mindset.jpg",
    lessons: 6,
    startDate: "Started Feb 1",
    progress: 100,
    isNew: false,
    instructor: communityMembers[2],
  },
  {
    id: "4",
    title: "Social Media Marketing",
    category: "Marketing",
    thumbnail: "/courses/social-media.jpg",
    lessons: 10,
    startDate: "Starts Apr 1",
    progress: 0,
    isNew: true,
    instructor: communityMembers[1],
  },
];

export const events = [
  {
    id: "1",
    title: "Weekly Q&A Session",
    host: communityMembers[0],
    thumbnail: "/events/qa-session.jpg",
    date: "Mar 18, 2026",
    time: "2:00 PM EST",
    type: "Live stream",
    isGoing: true,
    attendees: 45,
  },
  {
    id: "2",
    title: "Business Strategy Workshop",
    host: communityMembers[2],
    thumbnail: "/events/workshop.jpg",
    date: "Mar 20, 2026",
    time: "11:00 AM EST",
    type: "Workshop",
    isGoing: false,
    attendees: 28,
  },
  {
    id: "3",
    title: "Networking Mixer",
    host: communityMembers[4],
    thumbnail: "/events/mixer.jpg",
    date: "Mar 25, 2026",
    time: "6:00 PM EST",
    type: "In person",
    isGoing: false,
    attendees: 15,
  },
  {
    id: "4",
    title: "Course Launch Celebration",
    host: communityMembers[1],
    thumbnail: "/events/launch.jpg",
    date: "Mar 27, 2026",
    time: "3:00 PM EST",
    type: "Live stream",
    isGoing: true,
    attendees: 62,
  },
];

export const notifications = [
  {
    id: "1",
    type: "like",
    actor: communityMembers[0],
    message: "liked your post",
    target: "How I scaled my coaching business",
    timestamp: "5m ago",
    isRead: false,
  },
  {
    id: "2",
    type: "comment",
    actor: communityMembers[1],
    message: "commented on your post",
    target: "Weekly mindset challenge",
    timestamp: "1h ago",
    isRead: false,
  },
  {
    id: "3",
    type: "member",
    actor: communityMembers[6],
    message: "joined the community",
    target: null,
    timestamp: "3h ago",
    isRead: true,
  },
  {
    id: "4",
    type: "event",
    actor: communityMembers[4],
    message: "Event starting in 1 hour:",
    target: "Weekly Q&A Session",
    timestamp: "Yesterday",
    isRead: true,
  },
];

export const currentUser = {
  id: "current",
  name: "Sidd Ahmed",
  role: "Community Founder",
  avatar: "/avatars/sidd.jpg",
  email: "sidd@example.com",
  location: "Los Angeles, CA",
  bio: "Founder of this community. Helping people scale themselves with clarity and confidence.",
  memberSince: "Jan 2024",
  tags: ["Founder", "Business", "Coaching"],
  postsCount: 89,
  commentsCount: 234,
  spacesJoined: 12,
  isOnline: true,
  color: "bg-blue-600",
};
